# Generated by Django 5.2.1 on 2025-05-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0002_recipie_user_alter_recipie_recipie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='recipie_views',
            field=models.IntegerField(default=1),
        ),
    ]
