# Generated by Django 5.2.1 on 2025-05-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0007_subjectmarksold_delete_subjectmarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectMarksold',
        ),
    ]
