# Generated by Django 5.2.1 on 2025-05-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0009_subjectmarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectMarks',
        ),
    ]
