# Generated by Django 5.2.1 on 2025-05-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0012_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student_rank', 'date_of_report_card_generation')},
        ),
    ]
