# Generated by Django 5.1.9 on 2025-05-14 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0015_student_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportcard_set', to='vege.student'),
        ),
    ]
