# Generated by Django 5.1.9 on 2025-05-14 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0016_reportcard_total_marks_alter_reportcard_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcard',
            options={'ordering': ['-date_of_report_card_generation', 'student_rank']},
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('student', 'date_of_report_card_generation')},
        ),
    ]
