# Generated by Django 5.1.9 on 2025-05-14 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0017_alter_reportcard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depart', to='vege.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentid', to='vege.studentid'),
        ),
    ]
